// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlwz6KrACg6WYLzCttfUQknpWfhrGnDXk',
    appId: '1:13519750826:web:fe5d2045d8affd7341f2d3',
    messagingSenderId: '13519750826',
    projectId: 'intlakpanel',
    authDomain: 'intlakpanel.firebaseapp.com',
    databaseURL: 'https://intlakpanel-default-rtdb.firebaseio.com',
    storageBucket: 'intlakpanel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB92IiW4oarIlFWWpElwhbA81x7eEfP31g',
    appId: '1:13519750826:android:9cf9104d888eb83741f2d3',
    messagingSenderId: '13519750826',
    projectId: 'intlakpanel',
    databaseURL: 'https://intlakpanel-default-rtdb.firebaseio.com',
    storageBucket: 'intlakpanel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX1q5I_eVAaEPA02MrNVSU5lPGuiPJAM4',
    appId: '1:13519750826:ios:19598fab688b156d41f2d3',
    messagingSenderId: '13519750826',
    projectId: 'intlakpanel',
    databaseURL: 'https://intlakpanel-default-rtdb.firebaseio.com',
    storageBucket: 'intlakpanel.appspot.com',
    iosClientId: '13519750826-bn0boqthmipsi4othm3oho07kv4nnqgb.apps.googleusercontent.com',
    iosBundleId: 'com.bavandapps.weva',
  );
}
